#!/bin/sh

force=${1:-0.1}

rostopic pub /franka_gripper/grasp/goal franka_gripper/GraspActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  width: 0.0
  epsilon:
    inner: 1.0
    outer: 1.0
  speed: 0.04
  force: $force"
